//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basic_GUI_1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Basic_GUI_1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BenBack {
            get {
                object obj = ResourceManager.GetObject("BenBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BenFront {
            get {
                object obj = ResourceManager.GetObject("BenFront", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BowBack {
            get {
                object obj = ResourceManager.GetObject("BowBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BowFront {
            get {
                object obj = ResourceManager.GetObject("BowFront", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0, 0, 0},
        ///{30, 7, 2}, {1, 26, 9}, {26, 9, 28},
        ///{10, 5,11}, {29, 4, 6 }, {5, 11, 13},
        ///{1, 8, 13}, {7, 14, 15},{3, 2, 15},
        ///{4, 11, 17},{10, 4, 6}, {6, 17, 13},
        ///{7, 6, 18},{8, 20, 19}, {9, 8, 21},
        ///{21,22, 23}, {10, 23, 12}, {13,19, 14},
        ///{18, 25, 14}, {23, 14, 27},{15, 27,16}, 
        ///{16,29, 18}, {17, 16, 29}, {18, 30, 29},
        ///{20, 19, 26}, {24, 2, 3},{ 21, 20, 28},
        ///{22, 3, 27},{22, 23, 24},{1,5, 24},.
        /// </summary>
        internal static string CaveRoute1 {
            get {
                return ResourceManager.GetString("CaveRoute1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0, 0, 0},
        ///{25, 2, 6},{1, 26 ,3},{27, 2, 4}, 
        ///{3, 28, 5},{4, 29, 6}, {20, 1, 5}, 
        ///{12, 13, 8},{7, 14,9},{8, 15, 10},
        ///{9, 11, 17},{10, 17, 12},{13, 14, 19},
        ///{7, 19, 14},{8, 13, 20},{9, 16, 21},
        ///{15, 17, 22},{10, 11, 16},{12, 23, 24},
        ///{13, 20, 24},{14, 19, 21},{15, 20, 22},
        ///{16, 21, 23 },{18, 22, 24},{18, 19, 23},
        ///{30, 1, 26},{25, 2, 27 },{26, 3, 28},     
        ///{27, 4, 29},{28, 5, 30},{29, 6, 25},.
        /// </summary>
        internal static string CaveRoute2 {
            get {
                return ResourceManager.GetString("CaveRoute2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0, 0, 0},
        ///{7, 10, 2}, {1, 3, 8}, {2, 26, 9}, 
        ///{9, 10, 5}, {4, 11, 6}, {5, 12, 1}, 
        ///{1, 13, 8}, {7, 2, 24}, {3,15, 4},  
        ///{15, 4, 16}, {11, 23, 18}, {17, 12, 24}, 
        ///{19, 7, 8}, {13, 8, 20}, {9, 21, 16}, 
        ///{21, 22, 10}, {11, 23, 18}, {17, 12, 24},
        ///{13, 25, 20}, {29, 14, 26}, {15, 27, 16},
        ///{27, 16, 28}, {17, 29, 24}, {23, 30, 18},
        ///{30, 19, 26}, {25, 20, 3}, {21, 22, 28}, 
        ///{27, 22, 29}, {28, 23, 30}, {29, 24,1} 
        ///.
        /// </summary>
        internal static string CaveRoute3 {
            get {
                return ResourceManager.GetString("CaveRoute3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0, 0, 0},
        ///{30, 7, 2}, {1, 9, 3}, {26, 2, 4}, 
        ///{28, 3,10}, {28, 11, 6}, {5, 7, 11},
        ///{6, 1, 8}, {7, 14, 15}, {8, 15, 10},
        ///{9, 4, 17}, {3, 6, 12}, {11, 18, 13}, 
        ///{12, 19, 14}, {13, 8, 21}, {8, 9, 16}, 
        ///{15, 17, 23}, {10, 16, 18}, {17, 12, 19},
        ///{18, 13, 20}, {19, 25, 27}, {14, 27, 22},
        ///{21, 28, 29}, {16, 17, 23}, {23, 30, 25},
        ///{24, 20, 26}, {25, 27, 3}, {26, 20, 21}, 
        ///{22, 3, 5}, {22, 23, 30}, {29, 24, 25},  
        ///
        ///.
        /// </summary>
        internal static string CaveRoute4 {
            get {
                return ResourceManager.GetString("CaveRoute4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0, 0, 0},
        ///{6, 20, 25}, {7, 26,3}, {2, 26, 9},
        ///{9, 10, 5}, {4, 28, 29}, {11, 30, 1},
        ///{13, 8, 2}, {7,13,9}, {8,2,4},
        ///{15, 4, 11}, {10, 6, 12}, {11, 17,18}, 
        ///{7, 8, 14}, {13,19,15}, {14, 21, 10},
        ///{21, 22, 17 }, {16, 12, 18}, {17,23, 12},
        ///{24, 14, 20 }, {19, 25, 21}, {20, 15, 16},
        ///{27, 16, 23}, {22, 18, 24}, {23, 29, 19},
        ///{30, 1, 20}, {2, 3, 27},{26, 22, 28} ,
        ///{27, 29, 5}, {28, 5, 24,}, {6, 1, 7},
        ///
        ///.
        /// </summary>
        internal static string CaveRoute5 {
            get {
                return ResourceManager.GetString("CaveRoute5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Front {
            get {
                object obj = ResourceManager.GetObject("Front", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlainBack {
            get {
                object obj = ResourceManager.GetObject("PlainBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlainFront {
            get {
                object obj = ResourceManager.GetObject("PlainFront", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RedshirtBack {
            get {
                object obj = ResourceManager.GetObject("RedshirtBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RedshirtFront {
            get {
                object obj = ResourceManager.GetObject("RedshirtFront", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
